### ISSUE TITLE
Base styling html sturcture with all sections and some  shared css elements style

### ISSUE THREAD

**Issue by NerijusBun** [front-end-by-rimantas/43-grupe-portfolio-ewebot#10]
- base HTML structure with complete number of sections ()
-  ** Styling all repeating elements in web page**
- - font family
- - font color
- - font size 
- - p, h1..6, a..
- - container base style and layout
- - JS file with comments

**Comment by BaubasDRSK** [comment]
Teritorijos su komentarais pradiniam branche (develop) (po to kai sumerginsi failu brancha)
